### ISSUE TITLE
How to do multi-step training

### ISSUE THREAD

**Issue by miaomiaojun122** [Hi-FT/ERD#19]
When I do 40+20+20 multi-step training, I always report mistakes, tell me 
unexpected key in source state_dict: ori_model.backbone.conv1.weight, ori_model.backbone.bn1.weight, ori_model.backbone.bn1.bias, ori_model.backbone.bn1.running_mean, ori_model.backbone.bn1.running_var, ori_model.backbone.bn1.num_batches_tracked, ori_model.backbone.layer1.0.conv1.weight, ori_model.backbone.layer1.0.bn1.weight, ori_model.backbone.layer1.0.bn1.bias, ori_model.backbone.layer1.0.bn1.running_mean, ori_model.backbone.layer1.0.bn1.running_var, ori_model.backbone.layer1.0.bn1.num_batches_tracked, ori_model.backbone.layer1.0.conv2.weight, ori_model.backbone.layer1.0.bn2.weight, ori_model.backbone.layer1.0.bn2.bias, ori_model.backbone.layer1.0.bn2.running_mean, ori_model.backbone.layer1.0.bn2.running_var, ori_model.backbone.layer1.0.bn2.num_batches_tracked, ori_model.backbone.layer1.0.conv3.weight, ori_model.backbone.layer1.0.bn3.weight, ori_model.backbone.layer1.0.bn3.bias, ori_model.backbone.layer1.0.bn3.running_mean, ori_model.backbone.layer1.0.bn3.running_var, ori_model.backbone.layer1.0.bn3.num_batches_tracked, ori_model.backbone.layer1.0.downsample.0.weight, ......
How to do multi-step training
thank you

**Comment by NingYuHuang** [comment]
Have you solved this problem yet?

**Comment by miaomiaojun122** [comment]
> 你解决了这个问题吗？
解决了， 出现这个问题是因为参数没有改好。
例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。

**Comment by NingYuHuang** [comment]
> > 你解决了这个问题吗？
> > 解决了， 出现这个问题是因为参数没有改好。
> > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。

1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly
是我哪个位置没有修改到吗？

**Comment by miaomiaojun122** [comment]
> > > 你解决了这个问题吗？
> > > 解决了， 出现这个问题是因为参数没有改好。
> > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> 
> 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数

**Comment by NingYuHuang** [comment]
> > > > 你解决了这个问题吗？
> > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > 
> > 
> > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数

是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。

**Comment by miaomiaojun122** [comment]
> > > > > 你解决了这个问题吗？
> > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > 
> > > 
> > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> 
> 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。

我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗

**Comment by NingYuHuang** [comment]
> > > > > > 你解决了这个问题吗？
> > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > 
> > > > 
> > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > 
> > 
> > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> 
> 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗

这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。

**Comment by miaomiaojun122** [comment]
> > > > > > > 你解决了这个问题吗？
> > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > 
> > > > > 
> > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > 
> > > 
> > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > 
> > 
> > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> 
> 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下

> > > > > > > 你解决了这个问题吗？
> > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > 
> > > > > 
> > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > 
> > > 
> > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > 
> > 
> > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> 
> 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。

要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下

**Comment by NingYuHuang** [comment]
> > > > > > > > 你解决了这个问题吗？
> > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > 
> > > > > > 
> > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > 
> > > > 
> > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > 
> > > 
> > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > 
> > 
> > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
> > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> 
> > > > > > > > 你解决了这个问题吗？
> > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > 
> > > > > > 
> > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > 
> > > > 
> > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > 
> > > 
> > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > 
> > 
> > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。
> 
> 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下

设置了，还是不行。数据集太大了，我用的另一个4类数据集训练的。我还发现2+2的时候，旧的2类会忘掉。目前只有3+1没有忘掉。

**Comment by miaomiaojun122** [comment]
> > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > 
> > > > > > > 
> > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > 
> > > > > 
> > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > 
> > > > 
> > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > 
> > > 
> > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
> > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > 
> > 
> > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > 
> > > > > > > 
> > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > 
> > > > > 
> > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > 
> > > > 
> > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > 
> > > 
> > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。
> > 
> > 
> > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> 
> 设置了，还是不行。数据集太大了，我用的另一个4类数据集训练的。我还发现2+2的时候，旧的2类会忘掉。目前只有3+1没有忘掉。

你联系方式是什么呀，我加你一下，他报什么错呀

**Comment by NingYuHuang** [comment]
> > > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > > 
> > > > > > 
> > > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > > 
> > > > > 
> > > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > > 
> > > > 
> > > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
> > > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > > 
> > > 
> > > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > > 
> > > > > > 
> > > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > > 
> > > > > 
> > > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > > 
> > > > 
> > > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。
> > > 
> > > 
> > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > 
> > 
> > 设置了，还是不行。数据集太大了，我用的另一个4类数据集训练的。我还发现2+2的时候，旧的2类会忘掉。目前只有3+1没有忘掉。
> 
> 你联系方式是什么呀，我加你一下，他报什么错呀
478103025qq

**Comment by dream952118** [comment]
> > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > 
> > > > > > > 
> > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > 
> > > > > 
> > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > 
> > > > 
> > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > 
> > > 
> > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
> > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > 
> > 
> > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > 
> > > > > > > 
> > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > 
> > > > > 
> > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > 
> > > > 
> > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > 
> > > 
> > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。
> > 
> > 
> > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> 
> 设置了，还是不行。数据集太大了，我用的另一个4类数据集训练的。我还发现2+2的时候，旧的2类会忘掉。目前只有3+1没有忘掉。

你好，我用自己的數據集會出現以下錯誤，可能是什麼原因(用coco資料集跑不會有問題):

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Traceback (most recent call last):
  File "D:\ERD\tools\train.py", line 142, in <module>
    main()
  File "D:\ERD\tools\train.py", line 138, in main
    runner.train()
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\runner\runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\runner\runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\runner\loops.py", line 46, in __init__
    super().__init__(runner, dataloader)
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\runner\base_loop.py", line 27, in __init__
    self.dataloader = runner.build_dataloader(
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\runner\runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "d:\erd\mmdet\datasets\base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\dataset\base_dataset.py", line 247, in __init__
    self.full_init()
  File "d:\erd\mmdet\datasets\base_det_dataset.py", line 78, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "C:\Users\dream\anaconda3\envs\ERD\lib\site-packages\mmengine\dataset\base_dataset.py", line 770, in _serialize_data
    data_bytes = np.concatenate(data_list)
ValueError: need at least one array to concatenate

**Comment by dream952118** [comment]
> > > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > > 
> > > > > > 
> > > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > > 
> > > > > 
> > > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > > 
> > > > 
> > > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的
> > > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > > 
> > > 
> > > > > > > > > > 你解决了这个问题吗？
> > > > > > > > > > 解决了， 出现这个问题是因为参数没有改好。
> > > > > > > > > > 例如40+20+20 这种情况，先对40个类进行普通训练，再进行增量训练40+20，最后增量训练60+20，修改配置文件中相应的参数就可以了，需要把config，head和detector里的参数都修改一下。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1：普通训练40类；2：增量训练40+20；3：增量训练（40+20）+20。第三步，我修改了跟第二步相同的地方，但是失败了。显示RuntimeError: class `GFLIncrementERD` in mmdet/models/detectors/gfl_increment_erd.py: The model and loaded state dict do not match exactly 是我哪个位置没有修改到吗？
> > > > > > > > 需要将head和detector里的参数都修改一下self.num_classes=80，self.ori_num_classes=60，也就是gfl_head_increment_erd.py和gfl_increment_erd.py的参数
> > > > > > 
> > > > > > 
> > > > > > 是这样改的。是数据集划分的问题吗？ 第一步：普通训练40类，train40、val40。第二步：train40-60、val60。第三步：train60-80、val80。
> > > > > 
> > > > > 
> > > > > 我也是这样划分的，gfl_head_increment_erd.py和gfl_increment_erd.py都修改了吗
> > > > 
> > > > 
> > > > 这两个py文件里有要修改的内容吗？要修改哪里？我没有改，只改了configs/gfl_increment里的文件。
> > > 
> > > 
> > > 要修改的，self.num_classes=80，self.ori_num_classes=60，这样设置一下
> > 
> > 
> > 设置了，还是不行。数据集太大了，我用的另一个4类数据集训练的。我还发现2+2的时候，旧的2类会忘掉。目前只有3+1没有忘掉。
> 
> 你联系方式是什么呀，我加你一下，他报什么错呀

Hi, 我也想問要怎麼multi-step training，確定有改到self.num_classes, self.ori_num_classes兩個參數，是否需要更改其他的部分呢~?
